- type: job
  id: Mayor
  name: Мэр
  description: job-description-mayor
  playTimeTracker: JobMayor
  startingGear: MayorGear
  icon: "JobIconHeadOfPersonnel" #TODO: заменить иконку
  access:
    - Maintenance
    - Service
    - Cryogenics

- type: startingGear
  id: MayorGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
    jumpsuit: ClothingUniformJumpsuitColorGrey