- type: job
  id: OperativeBiotech
  name: Оперативник Биотехники
  description: job-description-operativeb
  playTimeTracker: JobOperativeB
  startingGear: OperativeBGear
  icon: "JobIconPassenger" #TODO: change icon
  access:   #TODO: change access
    - Maintenance
    - Service
    - Cryogenics

- type: startingGear
  id: OperativeBGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
    jumpsuit: ClothingUniformJumpsuitColorGrey