- type: job
  id: ChiefOfSecurityArasaka
  name: job-name-chief-security-arasaka
  description: job-description-chief-security-arasaka
  playTimeTracker: JobChiefOfSecurityArasaka
  startingGear: ChiefOfSecurityArasakaGear
  icon: "JobIconChiefOfSecurityArasaka" 
  supervisors: job-supervisors-hoda #TODO: change supervisors
  access: 
  - Arasaka
  - SecurityArasaka 
  - ArmoryArasaka
  - HeadOfDepartmentArasaka

- type: startingGear
  id: ChiefOfSecurityArasakaGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey

#TODO: