- type: job
  id: HeadOfDepartmentArasaka
  name: job-name-hoda
  description: job-description-hoda
  playTimeTracker: JobHeadOfDepartmentArasaka
  startingGear: HoDAGear 
  icon: "JobIconHeadOfDepartmentArasaka" 
  supervisors: job-supervisors-captain #TODO: change supervisors
  access:   #TODO: change access
  - Arasaka
  - SecurityArasaka 
  - ArmoryArasaka
  - HeadOfDepartmentArasaka

  #TODO: change gear
- type: startingGear
  id: HoDAGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
