- type: job
  id: MedicArasaka
  name: job-name-medic-arasaka
  description: job-description-medic-arasaka
  playTimeTracker: JobMedicArasaka
  startingGear: MedicArasakaGear
  icon: "JobIconMedicArasaka"
  supervisors: job-name-hoda #TODO: change supervisors
  access:   #TODO: change access
  - Medical
  - Command
  - Brig
  - Security
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics

- type: startingGear
  id: MedicArasakaGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey