- type: job
  id: OperativeArasaka
  name: job-name-operative-arasaka
  description: job-description-operative-arasaka
  playTimeTracker: JobOperativeArasaka
  startingGear: OperativeArasakaGear
  icon: "JobIconOperativeArasaka"
  supervisors: job-supervisors-squadcommander 

- type: startingGear
  id: OperativeArasakaGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
    head: ClothingHeadHelmetOperativeArasaka
    outerClothing: ClothingOuterArmorArasaka
    suitStorage: ClothingUniformJumpsuitHoSAlt
    shoes: ClothingShoesBootsCombat
    belt: ClothingBeltSecurity
