- type: job
  id: SecurityGuardArasaka
  name: job-name-securityguard-arasaka
  description: job-description-securityguard-arasaka
  playTimeTracker: JobSecurityGuardArasaka
  startingGear: SecurityGuardArasakaGear
  icon: "JobIconSecurityGuardArasaka" 
  supervisors: job-name-chief-security-arasaka #TODO: change supervisors
  access:   #TODO: change access
  - Security
  - Brig
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics

- type: startingGear
  id: SecurityGuardArasakaGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey

#TODO: add to role_loadout.yml