- type: job
  id: SquadCommanderArasaka
  name: job-name-squadcommander-arasaka
  description: job-description-squadcommander-arasaka
  playTimeTracker: JobSquadCommanderArasaka
  startingGear: SquadCommanderArasakaGear
  icon: "JobIconSquadCommanderArasaka"
  supervisors: job-supervisors-hoda #TODO: change supervisors
  access:   #TODO: change access
  - Arasaka
  - SecurityArasaka 
  - ArmoryArasaka
  - HeadOfDepartmentArasaka

- type: startingGear
  id: SquadCommanderArasakaGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
