- type: job
  id: TechnicianArasaka
  name: job-name-technician-arasaka
  description: job-description-technician-arasaka
  playTimeTracker: JobTechnicianArasaka
  startingGear: TechnicianArasakaGear
  icon: "JobIconTechnicianArasaka" 
  supervisors: job-name-hoda #TODO: change supervisors
  access:   #TODO: change access
  - Arasaka

- type: startingGear
  id: TechnicianArasakaGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey

#TODO: add to role_loadout.yml