- type: job
  id: WardenArasaka
  name: job-name-warden-arasaka
  description: job-description-warden-arasaka
  playTimeTracker: JobWardenArasaka
  startingGear: WardenArasakaGear
  icon: "JobIconWardenArasaka"
  supervisors: job-name-chief-security-arasaka #TODO: change supervisors
  access:   #TODO: change access
  - Arasaka
  - SecurityArasaka 
  - ArmoryArasaka

- type: startingGear
  id: WardenArasakaGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey