- type: job
  id: TraumaTeamChief
  name: Руководитель отдела TraumaTeam
  description: job-description-traumateam-chief
  playTimeTracker: JobTraumaTeamChief
  startingGear: TraumaTeamChiefGear
  access:
    - Maintenance
    - Service
    - Cryogenics

- type: startingGear
  id: TraumaTeamChiefGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
    jumpsuit: ClothingUniformJumpsuitColorGrey