- type: job
  id: TraumaTeamDoctor
  name: Врач TraumaTeam
  description: job-description-traumateam-doctor
  playTimeTracker: JobTraumaTeamDoctor
  startingGear: TraumaTeamDoctorGear
  icon: "JobIconMedicalDoctor" #TODO: заменить иконку
  access:
    - Maintenance
    - Service
    - Cryogenics

- type: startingGear
  id: TraumaTeamDoctorGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
    jumpsuit: ClothingUniformJumpsuitMedicalColorWhite