- type: job
  id: TraumaTeamOperative
  name: Оперативник TraumaTeam
  description: job-description-traumateam-operative
  playTimeTracker: JobTraumaTeamOperative
  startingGear: TraumaTeamOperativeGear
  access:
    - Maintenance
    - Service
    - Cryogenics

- type: startingGear
  id: TraumaTeamOperativeGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
    jumpsuit: ClothingUniformJumpsuitColorGrey