- type: job
  id: TraumaTeamParamedic
  name: Парамедик TraumaTeam
  description: job-description-traumateam-paramedic
  playTimeTracker: JobTraumaTeamParamedic
  startingGear: TraumaTeamParamedicGear
  access:
    - Maintenance
    - Service
    - Cryogenics

- type: startingGear
  id: TraumaTeamParamedicGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
    jumpsuit: ClothingUniformJumpsuitColorGrey