# Jobs Militech
- type: playTimeTracker
  id: JobHoDM

- type: playTimeTracker
  id: JobHoSM

- type: playTimeTracker
  id: JobMedTechM

- type: playTimeTracker
  id: JobOperativeM

- type: playTimeTracker
  id: JobSCM

- type: playTimeTracker
  id: JobSecM

# Jobs Civilian
- type: playTimeTracker
  id: JobCitizen

- type: playTimeTracker
  id: JobReaper

- type: playTimeTracker
  id: JobFixer

- type: playTimeTracker
  id: JobEdgeRunnerSolo
