- type: job
  id: SquadCommanderMilitech
  name: job-name-scm
  description: job-description-scm
  playTimeTracker: JobSCM
  startingGear: SquadCommanderMGear
  icon: "JobIconPassenger" #TODO: change icon
  access:   #TODO: change access
  - Maintenance
  - Service
  - Cryogenics


- type: startingGear
  id: SquadCommanderMGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
    jumpsuit: ClothingUniformJumpsuitColorGrey