- type: job
  id: NCPDOfficer
  name: Офицер полиции
  description: job-description-ncpd-officer
  playTimeTracker: JobNCPDOfficer
  startingGear: NCPDOfficerGear
  icon: "JobIconSecurityOfficer" #TODO: заменить иконку
  access:
    - Maintenance
    - Service
    - Cryogenics

- type: startingGear
  id: NCPDOfficerGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
    jumpsuit: ClothingUniformJumpsuitColorGrey