- type: job
  id: NCPDSWAT
  name: Спецназ NCPD
  description: job-description-ncpd-swat
  playTimeTracker: JobNCPDSWAT
  startingGear: NCPDSWATGear
  icon: "JobIconSecurityOfficer" #TODO: заменить иконку
  access:
    - Maintenance
    - Service
    - Cryogenics

- type: startingGear
  id: NCPDSWATGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
    jumpsuit: ClothingUniformJumpsuitColorGrey