- type: job
  id: EdgeRunnerNetRunner
  name: job-name-edgerunner-netrunner
  description: job-description-edgerunner-netrunner
  playTimeTracker: JobEdgeRunnerNetRunner
  startingGear: EdgeRunnerNetRunnerGear
  icon: "JobIconHeadOfSecurity" #TODO: change icon
  access:   #TODO: change access
  - Medical
  - Command
  - Brig
  - Security
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics

- type: startingGear
  id: EdgeRunnerNetRunnerGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey