- type: job
  id: EdgeRunnerSolo
  name: job-name-edgerunner-solo
  description: job-description-edgerunner-solo
  playTimeTracker: JobEdgeRunnerSolo
  startingGear: EdgeRunnerSoloGear
  icon: "JobIconHeadOfSecurity" #TODO: change icon
  access:   #TODO: change access
  - Medical
  - Command
  - Brig
  - Security
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics

- type: startingGear
  id: EdgeRunnerSoloGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey