- type: job
  id: Fixer
  name: job-name-fixer
  description: job-description-fixer
  playTimeTracker: JobFixer
  startingGear: FixerGear
  icon: "JobIconHeadOfSecurity" #TODO: change icon
  access:   #TODO: change access
  - Medical
  - Command
  - Brig
  - Security
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics

- type: startingGear
  id: FixerGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey