- type: job
  id: Reaper
  name: job-name-reaper
  description: job-description-reaper
  playTimeTracker: JobReaper
  startingGear: ReaperGear
  icon: "JobIconHeadOfSecurity" #TODO: change icon
  supervisors: job-name-hoda #TODO: change supervisors
  access:   #TODO: change access
  - Maintenance
  - Service
  - Cryogenics


- type: startingGear
  id: ReaperGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
    jumpsuit: ClothingUniformJumpsuitColorGrey