- type: job
  id: Citizen
  name: job-name-citizen
  description: job-description-citizen
  playTimeTracker: JobCitizenNC
  startingGear: CitizenGear
  icon: "JobIconHeadOfSecurity" #TODO: change icon
  access:   #TODO: change access
  - Maintenance
  - Service
  - Cryogenics

- type: startingGear
  id: CitizenGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
    jumpsuit: ClothingUniformJumpsuitColorGrey


