- type: job
  id: Builder
  name: Строитель
  description: job-description-builder
  playTimeTracker: JobBuilder
  startingGear: BuilderGear
  icon: "JobIconPassenger"
  access:
    - Maintenance
    - Service
    - Cryogenics

- type: startingGear
  id: BuilderGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
    jumpsuit: ClothingUniformJumpsuitEngineering
